#!/bin/sh

# # # # # # # # # # # # # # # # # # # #
#
# cDock-Helper
# Maintained By			: Wolfgang Baird
#
# # # # # # # # # # # # # # # # # # # #

log_dir="$HOME"/Library/"Application Support"/cDock/logs
if [[ ! -e "$log_dir" ]]; then mkdir -pv "$log_dir"; fi
exec &>"$log_dir"/helper.log

echo "Removing old files"
if [[ -e /Library/ScriptingAdditions/SIMBL.osax ]]; then rm -r /Library/ScriptingAdditions/SIMBL.osax; fi
if [[ -e /Library/Frameworks/Opee.framework ]]; then rm -r /Library/Frameworks/Opee.framework; fi
if [[ -e /Library/LaunchAgents/net.culater.SIMBL.Agent.plist ]]; then rm /Library/LaunchAgents/net.culater.SIMBL.Agent.plist; fi
if [[ -e /System/Library/ScriptingAdditions/SIMBL.osax ]]; then rm -r /System/Library/ScriptingAdditions/SIMBL.osax; fi
if [[ -e /System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist ]]; then rm /System/Library/LaunchAgents/net.culater.SIMBL.Agent.plist; fi

echo "Installing new files"
cp -r ./SIMBL.osax /System/Library/ScriptingAdditions/
cp -p /System/Library/ScriptingAdditions/SIMBL.osax/Contents/Resources/SIMBL\ Agent.app/Contents/Resources/net.culater.SIMBL.Agent.plist /System/Library/LaunchAgents/

echo "Starting SIMBL"
open /System/Library/ScriptingAdditions/SIMBL.osax/Contents/Resources/SIMBL\ Agent.app