#!/bin/bash

dockpid=$(pgrep -f "Dock.app")
newid=$dockpid

restart_SIMBL()
{
	killall "SIMBL Agent"
	sleep 1
	open ~/Library/Application\ Support/cDock/SIMBL\ Agent.app
}

restart_SIMBL

while [ 1 ]; do
	newid=$(pgrep -f "Dock.app")
	if [[ $newid != $dockpid ]]; then
		dockpid=$newid
		sleep 1; restart_SIMBL
	else
		sleep 1
	fi
done