#! /bin/bash

# # # # # # # # # # # # # # # # # # # #
#
# Maintained By	: Wolfgang Baird
# Version				: 3.0
# Updated				: Jun / 30 / 2014
#
# # # # # # # # # # # # # # # # # # # #

# Restart SIMBL Agent
restart_SIMBL() {
	restart_count=$(more /tmp/dmpipe)
	if [[ "$restart_count" == "QUIT" ]]; then
		echo "Shutting down process"
		sleep 2
		exit
	else
		restart_count=$((restart_count + 1))
		echo $restart_count >/tmp/dmpipe
		echo "restart count is now : "$restart_count
		{ open -a "$injec_path"; sleep 1; exit; } &
	fi
}

# Watch for crash loop
crash_monitor() {
	echo "Starting crash loop monitoring"
	sleep 35
	rs_count=$(more /tmp/dmpipe)
	if [[ $rs_count -gt 5 ]]; then
		echo "QUIT" >/tmp/dmpipe
	else
		echo 0 >/tmp/dmpipe
	fi
	echo "Stopping crash loop monitoring"
}

install_SIMBL() {
	if [[ ! -e /Library/ScriptingAdditions/SIMBL.osax || ! -e /Library/LaunchAgents/net.culater.SIMBL.Agent.plist ]]; then
		pass_res=$(ask_pass)
		mkdir -p /Library/Application Support/SIMBL/Plugins
		if [[ $pass_res = "_success" ]]; then
			sudo installer -verbose -pkg "$simbl_inst" -target /
			if [[ -e "$HOME/Library/Application Support/SIMBL/Plugins" ]]; then
				mv "$HOME/Library/Application Support/SIMBL/Plugins" "$HOME/Library/Application Support/SIMBL/Plugins.tmp"
				ln -s "/Library/Application Support/SIMBL/Plugins" "$HOME/Library/Application Support/SIMBL/Plugins"
				mv "$HOME/Library/Application Support/SIMBL/Plugins.tmp/"* "$HOME/Library/Application Support/SIMBL/Plugins"
				rm -r "$HOME/Library/Application Support/SIMBL/Plugins.tmp"
			else
				mkdir -p "/Library/Application Support/SIMBL/Plugins"
				ln -s "/Library/Application Support/SIMBL/Plugins" "$HOME/Library/Application Support/SIMBL/Plugins"
			fi
		fi
	fi
}

is_SIMBL_runnning() {
	simbl_id=$(ps ax | grep [M]acOS/SIMBL | sed -e 's/^[ \t]*//' | cut -f1 -d" ")
	if [[ -z $simbl_id ]]; then
		exec "/Library/ScriptingAdditions/SIMBL.osax/Contents/Resources/SIMBL Agent.app/Contents/MacOS/SIMBL Agent" &
		open -a "$injec_path"
	fi
}

#	Integers
total_count=0
restart_count=0
dockpid=0

#	Strings
resource_folder=$(cd "${0%/*}" && echo $PWD)
for i in {1..4}; do resource_folder=$(dirname "$resource_folder"); done

source "$resource_folder"/functions/shared_functions.sh

simbl_inst="$resource_folder/helpers/SIMBL-0.9.9.pkg"
injec_path="$resource_folder/helpers/cDock_injection.app"
wupdt_path="$resource_folder/updates/wUpdater.app/Contents/MacOS/wUpdater"
PlistBuddy=/usr/libexec/PlistBuddy" -c"
cdock_pl="$HOME"/Library/Preferences/org.w0lf.cDock.plist

scriptDirectory="$resource_folder"

#	App execution
echo $restart_count >/tmp/dmpipe
ask_pass
install_SIMBL
is_SIMBL_runnning

update_auto_install=$($PlistBuddy "Print autoInstall:" "$cdock_pl" 2>/dev/null || { $PlistBuddy "Add autoInstall integer 0" "$cdock_pl"; echo -n 0; } )
update_auto_check=$($PlistBuddy "Print autoCheck" "$cdock_pl" 2>/dev/null || { $PlistBuddy "Add autoCheck integer 1" "$cdock_pl"; echo -n 1; } )
curver=$($PlistBuddy "Print version" "$cdock_pl" 2>/dev/null || echo -n 1 )
if [[ $update_auto_check == 1 ]]; then
	update_check "$wupdt_path" "$resource_folder" "$curver" "$update_auto_install" "w" &
fi

# Main monitor loop
while [ 1 ]; do
	# Grab dockID
	newid=$(ps ax | grep [M]acOS/Dock | sed -e 's/^[ \t]*//' | cut -f1 -d" ")

	# If dock has been restarted it will have a new ID
	if [[ $newid != $dockpid ]]; then
		dockpid=$newid
		restart_SIMBL
		if [[ $restart_count -eq 1 ]]; then crash_monitor; fi &
		sleep 4
	else
		sleep 2 # Sleep time between checks
	fi
done

# END
