#!/bin/bash
echo -e "Restart Dock\nRestart Finder\nRestart cDock Agent"
if [[ $1 = "Restart Dock" ]]; then
	killall "Dock"
	say "Restarting Dock"
fi
if [[ $1 = "Restart Finder" ]]; then
	# Check for XtraFinder / TotalFinder
	if [[ $(lsof -c Finder | grep MacOS/XtraFinder) ]]; then 
		killall "Finder"
		open -b com.trankynam.XtraFinder
	elif [[ $(lsof -c Finder | grep MacOS/TotalFinder) ]]; then
		killall "Finder"
		open -b com.binaryage.totalfinder
	else
		killall "Finder"
	fi
	say "Restarting Finder"
fi
if [[ $1 = "Restart cDock Agent" ]]; then
	killall "Dock"
	killall -KILL "SIMBL"
	killall -KILL "cDock Agent"
	open -b org.w0lf.cDockAgent
	say "Restarting cDock Agent"
fi